Develop
arxoangel61/BasicJS pull request #1
Opened 2024-07-13 15:24 UTC by arxoangel61

Добрый день!

Для курса JS базовый сделал отдельный репозиторий.

Добавил задание 
4-navigator
5-languages
6-driver

2024-07-13 19:52 UTC, Levitinn requested changes

2024-07-13 19:52 UTC, Levitinn commented on 6-driver/script.js
зачем нужно сравнение? hasLicence == userLicence и isDrink == isDrinkUser?
если у тебя в переменной userLicence лежит true, то его не нужно сравнивать, само условие if (userLicence) уже сработает

2024-07-13 20:47 UTC, arxoangel61 commented on 6-driver/script.js
исправил

2024-07-15 19:18 UTC, Levitinn approved these changes

2024-07-15 19:18 UTC, Levitinn commented on 6-driver/script.js
> +let canDriver = ((age <= ageUser) && hasLicence && !isDrink);
((age <= ageUser) скобки лишние

2024-07-15 20:45 UTC, arxoangel61 commented on 6-driver/script.js
> +let canDriver = ((age <= ageUser) && hasLicence && !isDrink);
убрал ))

2024-07-15 20:46 UTC, merged