Develop
arxoangel61/BasicJS pull request #2
Opened 2024-07-19 13:09 UTC by arxoangel61

Добавил 7-8-9 задание.

2024-07-23 06:34 UTC, Levitinn requested changes

2024-07-23 06:34 UTC, Levitinn commented on 8-crypto/scripts.js
привет. в твоем решении, ты опираешься на конкретную длину строки. это не очень хорошо. ведь кож может быть любой длины, а не только 4,6,8. попробуй сделать так чтобы опираться на длину, но разбить строку пополам или на другие равные части, но при этом, учитывай, что длина может быть любая

2024-07-23 15:08 UTC, arxoangel61 commented on 8-crypto/scripts.js
отправил на проверку :) вроде сделал, то что требовалось

2024-07-25 08:15 UTC, Levitinn approved these changes

2024-07-25 08:15 UTC, Levitinn commented on 10-array-clean/scripts.js
> +    if(num > 5) {
можно сократить
return num > 5 ? false : true

2024-07-25 15:51 UTC, arxoangel61 commented on 10-array-clean/scripts.js
> +    if(num > 5) {
Спасибо. Поправил

2024-07-25 15:51 UTC, merged