Develop
arxoangel61/BasicJS pull request #3
Opened 2024-08-04 22:46 UTC by arxoangel61

Здравствуйте!

Задание 10 добавил исправление (ранее было принято).
Выполнил 11 задание.
Выполнил 12 задание.

Повозился с заданиями очень сильно. 12 пришлось искать доп информацию по алгоритму Луны, чтобы стало более понятно, как решать в математическом плане по перебору элементов.

2024-08-06 11:31 UTC, Levitinn requested changes

2024-08-06 11:31 UTC, Levitinn commented on 11-date-array/scripts.js
решение слиишком сложное и большое. давай думать как оптимизировать. это очень сложно переиспользовать и вообще на понимание нужно затратить значительное время. 
давай для начала попробуем привести каждую строку под к одному виду, например к этому '11/12/2023' или '11-12-2023' а затем, можно использовать new Date для проверки валидности даты. 
я лишь намекаю, придется немного подумать, но все таки это сильно сократит код ))

2024-08-06 11:31 UTC, Levitinn commented on 12-luna/script.js
> +        for(const elem of num) { // перебираем каждый символ и в случае не нахождения остатка от числа будет false
```
if(elem % 2 == 0 || elem % 2 == 1) {
    return true
}
return false
```

2024-08-06 11:31 UTC, Levitinn commented on 12-luna/script.js
> +    if(repearCard(card) == true) { // если элемент прошёл проверку то перебираем элемент на индекс и число
if (repearCard(card)) { ..... }

так будет правильнее

2024-08-06 13:29 UTC, arxoangel61 commented on 11-date-array/scripts.js
готово

2024-08-06 13:29 UTC, arxoangel61 commented on 12-luna/script.js
> +        for(const elem of num) { // перебираем каждый символ и в случае не нахождения остатка от числа будет false
Исправил

2024-08-06 13:29 UTC, arxoangel61 commented on 12-luna/script.js
> +    if(repearCard(card) == true) { // если элемент прошёл проверку то перебираем элемент на индекс и число
Исправил

2024-08-09 21:08 UTC, Levitinn approved these changes

2024-08-10 22:38 UTC, merged